#ATTAQUER BASE ROVIGO SQLSERVER

library(RODBC)
rov <- odbcConnect("ROVIGO_POWERPIVOT")
rov <- odbcConnect(dsn = "REF_PROD_COSMETO",uid = "esbguest",pwd = "esbguest",rows_at_time = 500)

library(RJDBC)


query_1 <- "SELECT  S.AAFAC, S.MMFAC, P.CORCH, P.COMDL, G.LNBINV5,G.LBFLE, SUM(S.QTARTEXP) as NBUNT
FROM DWH_PROD2_HOLDING.R_ARTICLE_GRP_DWH P
, DWH_PROD2_HOLDING.D_SORTIES_FRA_DWH S
, DWH_PROD2_HOLDING.R_HIEGEO_DWH G
, DWH_PROD2_HOLDING.R_CLASSE_COMMANDE_DWH C

WHERE S.COART = P.COART
AND S.COPAYFAC = G.COFLE
AND S.COCLSCMD = C.COCLSCMD

AND C.COGRE = 'R'
AND G.CONIV3 in ('EXP','EXPD')
AND P.COMDL in ('ECH', 'TST', 'VTE')
AND S.AAFAC = 2015

GROUP BY S.AAFAC, S.MMFAC,  P.CORCH, P.COMDL,G.LNBINV5,G.LBFLE
"
query2 <- ("SELECT COART,FLARTFLL,LBARTITN,COMRQ,COMDL,COBRA,COCYCVIE FROM T_ARTICLE_REF WHERE COARTITN IS NOT NULL")
query2 <- ("SELECT COART,COCYCVIE FROM T_ARTICLE_REF")

print("REQUETE EN COURS D'EXECUTION")

write.csv2(df,"C:/Users/ottavig/Desktop/extract.csv")